import { useSession } from "next-auth/react";
import Head from "next/head";
import React, { useState, type FC, type PropsWithChildren } from "react";
import { Auth } from "../templates/Auth";
import { Navbar } from "../shared/Navbar";
import { Sidebar } from "../shared/Sidebar";
import { usePostStore } from "~/store/post";
import { PostDialog } from "../shared/dialogs/PostDialog";
import { APP_NAME } from "~/common/constants/constants";

export const Layout: FC<PropsWithChildren> = ({ children }) => {
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useState(true);

  const openCreateDialog = usePostStore((state) => state.openCreateDialog);

  return (
    <>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-theme="light">
        {session ? (
          <>
            <div className="flex h-screen">
              {isOpen && <Sidebar />}
              <div className="flex flex-1 flex-col">
                <Navbar
                  onClickBar={() => setIsOpen(!isOpen)}
                  createProps={{
                    onShortClick: openCreateDialog,
                  }}
                />
                {children}
              </div>
            </div>
            <PostDialog />
          </>
        ) : (
          <Auth />
        )}
      </main>
    </>
  );
};
